var structures = {
    'ThermalPowerPlant': {
        "ID" : 1,
        "Name" : "Thermal Power Plant",
        "Terrain" : [1,2,4,32,64,128,512],
        "Cost" : 10000,
        "Power" : 1000,
        "Population" : -10,
        "Money" : -1500,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'WaterPowerPlant': {
        "ID" : 2,
        "Name" : "Water Power Plant",
        "Terrain" : [16,128],
        "Cost" : 15000,
        "Power" : 750,
        "Population" : -5,
        "Money" : -500,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'WindPowerPlant': {
        "ID" : 3,
        "Name" : "Wind Power Plant",
        "Terrain" : [2,64],
        "Cost" : 15000,
        "Power" : 250,
        "Population" : -1,
        "Money" : -300,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'TidalPowerPlant': {
        "ID" : 4,
        "Name" : "Tidal Power Plant",
        "Terrain" : [8,64],
        "Cost" : 10000,
        "Power" : 500,
        "Population" : -2,
        "Money" : -500,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'SolarPowerPlant': {
        "ID" : 5,
        "Name" : "Solar Power Plant",
        "Terrain" : [1],
        "Cost" : 20000,
        "Power" : 500,
        "Population" : -1,
        "Money" : -200,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'GeoThermalPowerPlant': {
        "ID" : 6,
        "Name" : "GeoThermal Power Plant",
        "Terrain" : [512],
        "Cost" : 20000,
        "Power" : 500,
        "Population" : -1,
        "Money" : -300,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'NuclearPowerPlant': {
        "ID" : 7,
        "Name" : "Nuclear Power Plant",
        "Terrain" : [64],
        "Cost" : 70000,
        "Power" : 3000,
        "Population" : -20,
        "Money" : -6000,
        "PopulationCap": 0,
        "Size" : 8,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'BitCoinMiner': {
        "ID" : 10,
        "Name" : "BitCoin Miner",
        "Terrain" : [1,2,4,32,64,128,512],
        "Cost" : 5000,
        "Power" : -2000,
        "Population" : -1,
        "Money" : 5000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'Sawmill': {
        "ID" : 11,
        "Name" : "Sawmill",
        "Terrain" : [4],
        "Cost" : 8000,
        "Power" : -500,
        "Population" : -10,
        "Money" : 2000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'FishFarm': {
        "ID" : 12,
        "Name" : "Fish Farm",
        "Terrain" : [8,16,64,128],
        "Cost" : 12000,
        "Power" : -200,
        "Population" : -5,
        "Money" : 2000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'ICFab': {
        "ID" : 13,
        "Name" : "IC Fab",
        "Terrain" : [1],
        "Cost" : 60000,
        "Power" : -2500,
        "Population" : -20,
        "Money" : 7000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'Pasture': {
        "ID" : 14,
        "Name" : "Pasture",
        "Terrain" : [2],
        "Cost" : 8000,
        "Power" : -100,
        "Population" : -30,
        "Money" : 2000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'Hotspring': {
        "ID" : 15,
        "Name" : "Hotspring",
        "Terrain" : [512],
        "Cost" : 0,
        "Power" : 0,
        "Population" : -2,
        "Money" : 1000,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    },
    'Residence': {
        "ID" : 20,
        "Name" : "Residence",
        "Terrain" : [1,2,4,32,64,128],
        "Cost" : 10000,
        "Power" : -200,
        "Population" : 0,
        "Money" : 0,
        "PopulationCap": 10,
        "Size" : 4,
        "MaxLevel": 1,
        "BuildTime": 10
    },
    'LargeResidence': {
        "ID" : 21,
        "Name" : "Large Residence",
        "Terrain" : [1,2,4,32,64,128],
        "Cost" : 10000,
        "Power" : -200,
        "Population" : 0,
        "Money" : 0,
        "PopulationCap": 50,
        "Size" : 8,
        "MaxLevel": 1,
        "BuildTime": 10
    },
    'MilitaryCamp': {
        "ID" : 22,
        "Name" : "Military Camp",
        "Terrain" : [1,2,4,32,64,128],
        "Cost" : 25000,
        "Power" : -400,
        "Population" : 2,
        "Money" : 0,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 1,
        "BuildTime": 10
    },
    'LargeMilitaryCamp': {
        "ID" : 23,
        "Name" : "Large Military Camp",
        "Terrain" : [1,2,4,32,64,128],
        "Cost" : 60000,
        "Power" : -500,
        "Population" : 4,
        "Money" : 0,
        "PopulationCap": 0,
        "Size" : 8,
        "MaxLevel": 1,
        "BuildTime": 10
    },
    'Observatory': {
        "ID" : 24,
        "Name" : "Observatory",
        "Terrain" : [1,2,4,32,64,128,512],
        "Cost" : 8000,
        "Power" : -100,
        "Population" : -2,
        "Money" : -500,
        "PopulationCap": 0,
        "Size" : 4,
        "MaxLevel": 5,
        "BuildTime": 10
    }
}

export default structures

